// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: session.proto

package sessionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackBehaviour int32

const (
	CallbackBehaviour_CALLBACK_BEHAVIOUR_RETAIN CallbackBehaviour = 0
	CallbackBehaviour_CALLBACK_BEHAVIOUR_DELETE CallbackBehaviour = 1
)

// Enum value maps for CallbackBehaviour.
var (
	CallbackBehaviour_name = map[int32]string{
		0: "CALLBACK_BEHAVIOUR_RETAIN",
		1: "CALLBACK_BEHAVIOUR_DELETE",
	}
	CallbackBehaviour_value = map[string]int32{
		"CALLBACK_BEHAVIOUR_RETAIN": 0,
		"CALLBACK_BEHAVIOUR_DELETE": 1,
	}
)

func (x CallbackBehaviour) Enum() *CallbackBehaviour {
	p := new(CallbackBehaviour)
	*p = x
	return p
}

func (x CallbackBehaviour) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallbackBehaviour) Descriptor() protoreflect.EnumDescriptor {
	return file_session_proto_enumTypes[0].Descriptor()
}

func (CallbackBehaviour) Type() protoreflect.EnumType {
	return &file_session_proto_enumTypes[0]
}

func (x CallbackBehaviour) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallbackBehaviour.Descriptor instead.
func (CallbackBehaviour) EnumDescriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

type PendingCallback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserData      string                 `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	HandlerRef    string                 `protobuf:"bytes,2,opt,name=handler_ref,json=handlerRef,proto3" json:"handler_ref,omitempty"`
	Behaviour     CallbackBehaviour      `protobuf:"varint,3,opt,name=behaviour,proto3,enum=sessionpb.CallbackBehaviour" json:"behaviour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingCallback) Reset() {
	*x = PendingCallback{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingCallback) ProtoMessage() {}

func (x *PendingCallback) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingCallback.ProtoReflect.Descriptor instead.
func (*PendingCallback) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *PendingCallback) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *PendingCallback) GetHandlerRef() string {
	if x != nil {
		return x.HandlerRef
	}
	return ""
}

func (x *PendingCallback) GetBehaviour() CallbackBehaviour {
	if x != nil {
		return x.Behaviour
	}
	return CallbackBehaviour_CALLBACK_BEHAVIOUR_RETAIN
}

type UserContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Misc          *structpb.Struct       `protobuf:"bytes,6,opt,name=misc,proto3" json:"misc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContext) Reset() {
	*x = UserContext{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContext) ProtoMessage() {}

func (x *UserContext) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContext.ProtoReflect.Descriptor instead.
func (*UserContext) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *UserContext) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserContext) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *UserContext) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserContext) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserContext) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserContext) GetMisc() *structpb.Struct {
	if x != nil {
		return x.Misc
	}
	return nil
}

type Session struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	ExpireTime       *timestamppb.Timestamp      `protobuf:"bytes,1,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Ttl              int64                       `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	UserId           int64                       `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentStage     string                      `protobuf:"bytes,4,opt,name=current_stage,json=currentStage,proto3" json:"current_stage,omitempty"`
	Context          *UserContext                `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	PendingCallbacks map[string]*PendingCallback `protobuf:"bytes,6,rep,name=pending_callbacks,json=pendingCallbacks,proto3" json:"pending_callbacks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PendingInputs    map[string]string           `protobuf:"bytes,7,rep,name=pending_inputs,json=pendingInputs,proto3" json:"pending_inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StageMessages    []int64                     `protobuf:"varint,8,rep,packed,name=stage_messages,json=stageMessages,proto3" json:"stage_messages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

func (x *Session) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Session) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Session) GetCurrentStage() string {
	if x != nil {
		return x.CurrentStage
	}
	return ""
}

func (x *Session) GetContext() *UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Session) GetPendingCallbacks() map[string]*PendingCallback {
	if x != nil {
		return x.PendingCallbacks
	}
	return nil
}

func (x *Session) GetPendingInputs() map[string]string {
	if x != nil {
		return x.PendingInputs
	}
	return nil
}

func (x *Session) GetStageMessages() []int64 {
	if x != nil {
		return x.StageMessages
	}
	return nil
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\tsessionpb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8b\x01\n" +
	"\x0fPendingCallback\x12\x1b\n" +
	"\tuser_data\x18\x01 \x01(\tR\buserData\x12\x1f\n" +
	"\vhandler_ref\x18\x02 \x01(\tR\n" +
	"handlerRef\x12:\n" +
	"\tbehaviour\x18\x03 \x01(\x0e2\x1c.sessionpb.CallbackBehaviourR\tbehaviour\"\xb4\x01\n" +
	"\vUserContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12+\n" +
	"\x04misc\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04misc\"\xb7\x04\n" +
	"\aSession\x12;\n" +
	"\vexpire_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x03R\x03ttl\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12#\n" +
	"\rcurrent_stage\x18\x04 \x01(\tR\fcurrentStage\x120\n" +
	"\acontext\x18\x05 \x01(\v2\x16.sessionpb.UserContextR\acontext\x12U\n" +
	"\x11pending_callbacks\x18\x06 \x03(\v2(.sessionpb.Session.PendingCallbacksEntryR\x10pendingCallbacks\x12L\n" +
	"\x0epending_inputs\x18\a \x03(\v2%.sessionpb.Session.PendingInputsEntryR\rpendingInputs\x12%\n" +
	"\x0estage_messages\x18\b \x03(\x03R\rstageMessages\x1a_\n" +
	"\x15PendingCallbacksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.sessionpb.PendingCallbackR\x05value:\x028\x01\x1a@\n" +
	"\x12PendingInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*Q\n" +
	"\x11CallbackBehaviour\x12\x1d\n" +
	"\x19CALLBACK_BEHAVIOUR_RETAIN\x10\x00\x12\x1d\n" +
	"\x19CALLBACK_BEHAVIOUR_DELETE\x10\x01B,Z*github.com/atsegelnyk/galaxia/pb;sessionpbb\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_session_proto_goTypes = []any{
	(CallbackBehaviour)(0),        // 0: sessionpb.CallbackBehaviour
	(*PendingCallback)(nil),       // 1: sessionpb.PendingCallback
	(*UserContext)(nil),           // 2: sessionpb.UserContext
	(*Session)(nil),               // 3: sessionpb.Session
	nil,                           // 4: sessionpb.Session.PendingCallbacksEntry
	nil,                           // 5: sessionpb.Session.PendingInputsEntry
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_session_proto_depIdxs = []int32{
	0, // 0: sessionpb.PendingCallback.behaviour:type_name -> sessionpb.CallbackBehaviour
	6, // 1: sessionpb.UserContext.misc:type_name -> google.protobuf.Struct
	7, // 2: sessionpb.Session.expire_time:type_name -> google.protobuf.Timestamp
	2, // 3: sessionpb.Session.context:type_name -> sessionpb.UserContext
	4, // 4: sessionpb.Session.pending_callbacks:type_name -> sessionpb.Session.PendingCallbacksEntry
	5, // 5: sessionpb.Session.pending_inputs:type_name -> sessionpb.Session.PendingInputsEntry
	1, // 6: sessionpb.Session.PendingCallbacksEntry.value:type_name -> sessionpb.PendingCallback
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		EnumInfos:         file_session_proto_enumTypes,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
